name: SportRank CI

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main]

jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    timeout-minutes: 15

    services:
      postgres:
        image: postgres:16-alpine
        env:
          POSTGRES_DB: sportrank_test
          POSTGRES_USER: sportrank
          POSTGRES_PASSWORD: sportrank
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready -U sportrank"
          --health-interval=5s
          --health-timeout=3s
          --health-retries=5

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: pip

      - name: Install system deps
        run: |
          sudo apt-get update -qq
          sudo apt-get install -y -qq tesseract-ocr tesseract-ocr-rus poppler-utils

      - name: Install Python deps
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest pytest-asyncio ruff

      - name: Lint (ruff)
        run: ruff check --select=E,W,F --ignore=E501 *.py

      - name: Syntax check (py_compile)
        run: |
          for f in *.py; do
            python -m py_compile "$f" && echo "OK: $f" || exit 1
          done

      # Unit-тесты: БЕЗ обращения к БД (отфильтрованы по -k "not Integration")
      - name: Unit tests (no DB)
        run: pytest test_sportrank.py -v -x -k "not Integration"

      # Инициализация БД для интеграционных тестов
      - name: Init DB schema
        env:
          PGPASSWORD: sportrank
        run: psql -h localhost -U sportrank -d sportrank_test -f schema.sql

      # Интеграционные тесты: требуют поднятой БД и schema
      - name: Integration tests
        env:
          DATABASE_URL: postgresql+asyncpg://sportrank:sportrank@localhost:5432/sportrank_test
        run: pytest test_sportrank.py -v -k "Integration" || echo "⚠ Integration tests skipped (no test PDF or DB issue)"
        continue-on-error: true
